import './globals.css'
import type { Metadata } from 'next'
import { Ubuntu } from 'next/font/google'
import Header from './components/Header'
import Providers from './Providers'
import Footer from './components/Footer'

const ubuntu = Ubuntu({ subsets: ['latin'], weight: ['300'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={ubuntu.className} cz-shortcut-listen="true">
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
